mozilla/jetstream

- .circleci/config.yml
This PR adds an automated deploy step to CI that builds the docker image and uploads it to the GCP project's container registry. Modeled using the deployment step in mozilla/forecasting
I added all the environment vars required to the project already so hopefully when this is merged in we'll see an auto-deploy..
> Add automated deployment of docker image to google container registry

- pensieve/analysis.py
- pensieve/experimenter.py
- pensieve/tests/test_analysis.py
- script/run_experiment_analysis
The fix is to skip experiments defined without an enrollment period. I think mozanalysis should handle this case more politely (cf https://github.com/mozilla/mozanalysis/issues/74) but I think that trying to analyze experiments without an enrollment period probably doesn't make any sense in this model of analysis.
This PR adds a --dry_run flag and some logging. (How dry should dry be? We could ask BigQuery to validate the query for us -- right now I'm just returning early and avoiding the BQ call.)
> Add logging, fix bustage

- pensieve/__init__.py
- pensieve/analysis.py
- pensieve/config.py
- pensieve/tests/integration/test_analysis_integration.py
- pensieve/tests/test_config.py
We're iterating over the keys often enough that we might as well just make it official instead of calling getattr() so much.
I don't feel really strongly about this; I don't love that it makes the Spec/Configuration story a little weaker but I'm pleased that it's straightforward to specify and feels a little less hacky.
I also don't really like using Sets here anymore, because they imply that adding a Metric is safe; it's possible to have non-identical Metrics with the same `name`, so a Set is not guaranteed not to have collisions, and testing whether a metric is already in the set is probably not useful.
Up to you!
> MetricsConfiguration is just an enum-typed dict

- default_metrics.toml
- pensieve/cli.py
- pensieve/config.py
- pensieve/tests/test_config.py
This addresses https://github.com/mozilla/pensieve/pull/36#discussion_r418602423 and depends on https://github.com/mozilla/pensieve/pull/36
I moved all the default and available metrics to a `default_metrics.toml` file so that these do not need to be hardcoded and can be updated in a more convenient way.
> Statistics metrics config

- pensieve/cli.py
- pensieve/experimenter.py
- pensieve/tests/test_cli.py
- pensieve/tests/test_experimenter.py
Addresses https://github.com/mozilla/pensieve/issues/59
I added some options to the CLI `run` command that allow to specify running the analysis only on a specific experiment and on a specific date range.  I also added a `rerun` option to re-run all analyses for a specific experiment starting at the experiment `start_date`.
> Facilitate (re)running previous analyses for an experiment

- pensieve/cli.py
- pensieve/config.py
Restore the `pensieve run --date=` option. Makes `--date` required.
Closes #75.
> Restore date option

- pensieve/analysis.py
- pensieve/tests/conftest.py
- pensieve/tests/test_analysis.py
The experiment's end_date is the proposed end_date until the experiment actually ends. Then, end_date is updated to the date the experiment ended. The day before the experiment ends is the last date of complete data.
Fixes #99.
> Don't run overall analysis until the experiment's complete

- pensieve/analysis.py
- pensieve/statistics.py
- pensieve/tests/test_statistics.py
`comparison` records the comparison being made; `comparison_to_branch` 
records to which branch the comparison is relative.
Moves the BigQuery schema for statistics onto the StatisticResult object 
to make it easier to keep them in sync.
@emtwo, can you ptal? This is a backwards-incompatible schema change for the statistics tables.
Closes #105.
> Allow statistics tables to represent comparisons between treatment branches

- pensieve/analysis.py
- pensieve/statistics.py
- pensieve/tests/integration/test_analysis_integration.py
- pensieve/tests/test_statistics.py
Add a special statistic that counts the number of clients enrolled in each branch. It doesn't depend on the value of any of the metrics columns -- just the number of rows for each branch, since each metrics table will have one row per client per branch.
It's awkward to express in configuration since it doesn't have a corresponding metric and it seems in poor form to invent one.
It should be the same for all statistics tables for an experiment (but may not be, because of Shredder).
> Add a count statistic

- bin/entrypoint
- pensieve/analysis.py
- pensieve/cli.py
- pensieve/config.py
- pensieve/external_config.py
- pensieve/tests/integration/test_external_config_integration.py
- pensieve/tests/test_external_config.py
- requirements.in
- requirements.txt
- setup.py
This adds support to pull in configs from [pensieve-config](https://github.com/mozilla/pensieve-config/)
I already set up pensieve-config to trigger pensieve when a PR gets merged. It will trigger a cloud function which spins up a GCE instance running pensieve.  I should probably put the script for this somewhere...
As follow-ups to this PR we should look into a way to shutdown GCE instances when they are done with running pensieve and in cases of errors, notifying users. Right now there is no indicator when things go wrong or are done, data just appears in the tables.
> Pensieve external config integration

- jetstream/cli.py
This can be used in https://github.com/mozilla/jetstream-config/blob/1dbf20fb8860b9051fe0e57c2aa31550f3dff912/.circleci/config.yml#L9 to validate config files added to the [jetstream-config](https://github.com/mozilla/jetstream-config) repository.
See https://github.com/mozilla/jetstream/issues/107
> Add CLI command for validating config files

- jetstream/config.py
- jetstream/tests/conftest.py
- jetstream/tests/test_config.py
Specifying experiment.control_branch in the configuration file will override data in Experimenter. This is a workaround for #130; we'll need something like this as part of enabling all-pairwise-comparisons anyway.
> Allow users to override control branch slug

- jetstream/cli.py
Creating the dummy experiment with a slug field was throwing an exception. I think we don't need it anymore if we're doing a dry run.
> Fix validate_config command

- jetstream/analysis.py
- jetstream/cli.py
- jetstream/dryrun.py
- jetstream/tests/test_analysis.py
Fixes #210, probably moots #129. 
Writes a single query for the overall experiment in order to check the edges of the windows and all of the metrics.
This probably needs some tests; we might need to remove most of the existing dry_run options in the Analysis class since we're no longer using them.
Ironically it's a little WET but I don't think the copypasta is too bad unless you see an obvious refactoring opportunity.
> Validate all metrics

- jetstream/analysis.py
- jetstream/config.py
- jetstream/errors.py
- jetstream/tests/test_analysis.py
- jetstream/tests/test_config.py
Part of #58.
Lets you write configurations like:
```toml
[experiment]
segments = ["regular_users_v3", "my_cool_segment"]
[segments.my_cool_segment]
data_source = "my_cool_data_source"
select_expression = "{{agg_any('1')}}"
[segments.data_sources.my_cool_data_source]
from_expression = "(SELECT 1)"
```
Resolved segments end up in the list `ExperimentConfiguration.segments`.
> Allow segment definitions

- jetstream/__init__.py
- jetstream/analysis.py
- jetstream/external_config.py
ExternalConfig.updated_configs() would return an empty list because it was looking for tables that could never exist; dashes are common in Normandy slugs and they need to be normalized to underscores.
> Normalize slugs to table names

- jetstream/cli.py
Avoids a problem where Click doesn't line up the arguments the way we expected.
> Pass arguments by name

- jetstream/analysis.py
- jetstream/bigquery_client.py
- jetstream/cli.py
- jetstream/tests/integration/conftest.py
Related to https://github.com/mozilla/jetstream/issues/235
I noticed that for the `bug-1647305-pref-comcast-steering-experiment-release-78-80` Jetstream has been triggering a complete re-run the past couple of days. The reason for this is that before there was a custom config, Jetstream had already created tables for previous analysis runs, including some for days 23 and 24. With [the new `end_date`](https://github.com/mozilla/jetstream-config/blob/0b86aaedb888cd8222cf5f51c4959e2dfb573595/bug-1647305-pref-comcast-steering-experiment-release-78-80.toml#L2) in the custom config, these two days are excluded and did not get analysed when a re-run was triggered. However, since these tables still existed and their `last_updated` timestamp was older than the custom configs creation date, …
> Delete tables on re-run that have been previously created for experiment

- jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/231
This should ensure that the jetstream-config CircleCI step shows a failure when jetstream throws exceptions
> Error status code when exceptions are thrown during rerun

- jetstream/statistics.py
Means are dangerous because they take outlier clients too seriously. This drops the highest ten-thousandth of values before computing means. Data scientists can override it by specifying drop_highest = 0.
Closes #222.
> Drop the highest readings by default for means

- jetstream/external_config.py
I guess testing this is hard without building some mocks or an integration repo, but maybe we should consider that, and find a way to enforce aware-datetime constraints with typing.
> Localize commit datetimes to UTC

- jetstream/cli.py
We should avoid returning an error status code for now as long as Jetstream runs in Airflow. Currently, if there is some exception being thrown it'll mark the Airflow job as failed and retry it several times. Even if the exception is something we want to ignore, like `NoEnrollmentPeriodException`.
> Mute sys.exit for Airflow

- jetstream/argo.py
Should fix https://github.com/mozilla/jetstream/issues/313
I tested this with a separate service account that has the same permissions as the Airflow account. It worked at least locally for me without problems.
> Fix Argo credential refresh

- jetstream/argo.py
- jetstream/cli.py
Used in https://github.com/mozilla/telemetry-airflow/pull/1186
I realized that it might not be possible to grant Compute Engine API access to the Airflow cluster without deleting and creating a new cluster that has the necessary permissions. So this is potentially something data ops might not be willing to do. Fortunately, I also found a workaround. We can pass in the Jetstream Kubernetes cluster IP and certificate used for authenticating to the cluster and don't need Compute Engine API access for this. Both the IP and certificate can be stored as Airflow variables.
> Provide options to pass cluster IP and certificate

- Dockerfile
- bin/entrypoint
- jetstream/analysis.py
- jetstream/argo.py
- jetstream/bigquery_client.py
- jetstream/cli.py
- jetstream/config.py
- jetstream/dryrun.py
- jetstream/experimenter.py
- jetstream/export_json.py
- jetstream/external_config.py
- jetstream/logging/bigquery_log_handler.py
- jetstream/nimbus.py
- jetstream/pre_treatment.py
- jetstream/statistics.py
- jetstream/tests/conftest.py
- jetstream/tests/integration/conftest.py
- jetstream/tests/integration/test_analysis_integration.py
- jetstream/tests/integration/test_external_config_integration.py
- jetstream/tests/integration/test_logging_integration.py
- jetstream/tests/test_analysis.py
- jetstream/tests/test_argo.py
- jetstream/tests/test_cli.py
- jetstream/tests/test_config.py
- jetstream/tests/test_experimenter.py
- jetstream/tests/test_statistics.py
- jetstream/util.py
- requirements.in
- requirements.txt
- setup.py
Supersedes https://github.com/mozilla/jetstream/pull/299
I ran some benchmarks to see how much speedup this gives us. The actual speedup depends on available CPU resources, but I got up to a 50% speed increase for computation intensive tasks (e.g. the weekly analysis run for `bug-1664289-pref-activity-stream-pocket-new-tab-en-global-feed-release-81-82` and `bug-1665555-pref-etp4-retention-study-release-81-83`).
An even better solution here would be to use [Dask Kubernetes](https://kubernetes.dask.org/en/latest/) which would deploy Dask workers on the cluster instead of just the single pod running the analysis for an experiment. I did try to get this working, however was unable to get the Dask cluster manager working. It's probably worth keeping this option in mind for future improvements …
> Run analysis steps in parallel with Dask

- jetstream/experimenter.py
- jetstream/tests/test_experimenter.py
Now that there are V6 experiments, jetstream is throwing the following error:
`'ERROR:2020-11-16 20:38:51,025:jetstream.experimenter:unconverted data remains: T20:05:16.271480Z\n'`
The date format returned by the Experimenter V6 API is something like `2020-07-29T20:05:16.271480Z`
> Fix Experimenter API V6 date parsing

- jetstream/analysis.py
- jetstream/tests/integration/test_analysis_integration.py
A local "rerun" should keep using the same dask cluster. Clusters survive deletion so this avoids spawning several at once.
Also adds a secret JETSTREAM_PROCESSES environment variable to limit the number of worker processes.
> Reuse Dask cluster

- jetstream/external_config.py
- jetstream/tests/integration/test_external_config_integration.py
Currently we aren't rerunning experiments if their configuration changes but they've never been run before.
> Mark experiments without tables as changed when their config updates

- jetstream/analysis.py
- jetstream/config.py
- jetstream/tests/test_config.py
For certain experiment designs (e.g. holdbacks), it's useful to lie to Jetstream about when an experiment launched.
We'll use this in https://github.com/mozilla/jetstream-config/pull/20. cc @teonbrooks
> Allow start_date override

- jetstream/statistics.py
- jetstream/tests/test_statistics.py
kde.evaluate always returns an ndarray, not a scalar, even when the argument is a scalar.
I assume statsmodels doesn't have type annotations, so mypy didn't catch this.
The error message we got for this crash wasn't great because we didn't notice the error until the BigQuery API tried to serialize the output to JSON and didn't accept the ndarray. Should we make runtime assertions about types when we construct the StatisticsResult?
> Don't crash on log-space KDEs

- bin/entrypoint
jetstream-config calls rerun-config-changed via the entrypoint script. Currently, it just ignores all parameters and flags.
See https://github.com/mozilla/jetstream-config/pull/38
> Allow parameters for rerun-config-changed in entrypoint

- jetstream/argo.py
Should fix last nights Airflow errors. The run still successfully completed in Argo, but extracting the workflow status caused some problems:
```
[2021-01-06 05:06:09,571] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-01-06 05:06:09,571] {pod_launcher.py:156} INFO - b'  File "/usr/local/bin/jetstream", line 8, in <module>\n'
[2021-01-06 05:06:09,571] {pod_launcher.py:156} INFO - b'    sys.exit(cli())\n'
[2021-01-06 05:06:09,571] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__\n'
[2021-01-06 05:06:09,572] {pod_launcher.py:156} INFO - b'    return self.main(*args, **kwargs)\n'
[2021-01-06 05:06:09,572] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/site-packages/click/core.py", …
```
> Fix Argo workflow status extraction

- .circleci/config.yml
The `build-and-push-image` CI step is currently failing with:
```
ERROR: (gcloud.config.set) Some requests did not succeed:
- Required 'compute.zones.list' permission for 'projects/***********************'
```
We actually ran into a very similar issue in telemetry-airflow (same error, but syncing to GCS instead of publishing images), which was fixed in https://github.com/mozilla/telemetry-airflow/pull/1222. Apparently GCP broke something with their latest cloud SDK image. Not sure if this will actually fix the issue, it's hard to test the image publishing step locally. But I guess we should update this anyway at some point.
Edit: This probably won't fix the issue since gcp-gcr downloads the most recent cloud SDK image, which is broken.
> Update CircleCI deploy step

- jetstream/workflows/run.yaml
This updates the Argo workflow to run the json export immediately after the analysis has been completed for an experiment. Currently, Argo is waiting for all experiment analyses to finish and then runs the json data export. This can result in a delay of data being available if there is an analysis running that takes very long.
> Argo workflow: don't wait for all analyses to finish before exporting json

- jetstream/cli.py
- jetstream/errors.py
Fixes https://github.com/mozilla/jetstream/issues/454
Currently, if Jetstream raises one of [its custom exceptions](https://github.com/mozilla/jetstream/blob/main/jetstream/errors.py) Argo will retry the task several times even though none of the retries will ever succeed. This results in some scary looking graphs in Argo although nothing bad is actually happening. If there was, we'd get an alert.
So to prevent Argo from retrying, this PR will change Jetstream's behaviour to return a success state when a task raises a custom `JetstreamException`. 
This will potentially reduce the time Jetstream requires to complete it's daily analysis and reduce the number of pods Kubernetes spawns. One downside is that looking at the Argo interface it will not be immediately apparent if a task succeeded …
> Don't let tasks fail when custom Jetstream exception is raised

- jetstream/config.py
- jetstream/tests/test_config.py
@SuYoungHong pointed out that we don't support data sources without an experiments column in jetstream-config because mozanalysis expects an explicit `None` value and TOML can't encode it.
> Support data_sources with no experiments column

- jetstream/external_config.py
Depends on https://github.com/mozilla/jetstream-config/pull/47
> External example configs have .toml.example endings

- jetstream/external_config.py
Fixes validation errors in https://github.com/mozilla/jetstream-config/pull/47
> Fix slug parsing from external configs

- jetstream/cli.py
Validating an experiment with a skip directive fails because it isn't runnable. We shouldn't act like there's an error when we're doing something the user asked us to do.
> Skipped experiments should validate

- jetstream/analysis.py
Fixes https://github.com/mozilla/jetstream/issues/550
Since we still want the result in `moz-fx-data-experiments` simply changing the project ID to shared prod would mean that all result tables are written to `mozanalysis` in shared-prod. Instead a temporary workaround is to just run the metrics query in shared prod and copy the result tables around. Once the BigQuery issues are resolved we can undo the changes here.
> Run metrics queries in shared-prod

- jetstream/experimenter.py
- jetstream/tests/test_experimenter.py
I misunderstood how cattrs and attrs interacted with respect to _prefixed attributes.
attrs expects the attributes to appear in the constructor without a prefix. cattrs expects the attributes to appear in the dictionary with a prefix!
```python
>>> import cattr
>>> import attr
>>> @attr.s(auto_attribs=True)
... class A:
...   _foo: str
...
>>> A(foo="bar")
A(_foo='bar')
>>> cattr.structure({"_foo": "bar"}, A)
A(_foo='bar')
>>> cattr.structure({"foo": "bar"}, A)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/tsmith/projects/jetstream/venv/lib/python3.9/site-packages/cattr/converters.py", line 205, in structure
return self._structure_func.dispatch(cl)(obj, cl)
File "/Users/tsmith/projects/jetstream/venv/lib/python3.9/site-packages/cattr/converters.py", …
```
> Fix Fenix experiment analysis

- jetstream/tests/test_cli.py
Mitigates and probably closes #409 -- I'd like to be able to handle some of these with injection somehow but this is also fine.
results of `tox -e py38 -- -k test_cli --durations=0`
before:
```
============================================================================================= slowest durations =============================================================================================
8.08s call     .tox/py38/lib/python3.8/site-packages/jetstream/tests/test_cli.py::TestCli::test_validate_example_outcome_config
7.58s call     .tox/py38/lib/python3.8/site-packages/jetstream/tests/test_cli.py::TestSerialExecutorStrategy::test_trivial_workflow
5.50s call     .tox/py38/lib/python3.8/site-packages/jetstream/tests/test_cli.py::TestSerialExecutorStrategy::test_simple_workflow
3.83s …
```
> Avoid hitting the network in unit tests

- jetstream/argo.py
We had a bunch of jetstream-config failures which made me aware of this problem: jetstream was checking the status of each pod but didn't take into account that argo might do a successful retry. So whenever a step failed, jetstream returned a failed status code, although the step did succeed in a retry.
> Fix argo status check of failed pods

- jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/577
For experiments that are marked as `skip=true` in the config, Jetstream currently always includes them in the worklist of experiments to be analyzed. Every time, pods are created that result in the `SkippedException` being thrown. 
This is especially problematic when rerunning experiments with changed configs. Since no table will ever be created for skipped experiments, Jetstream always thinks the config has changed and tries to rerun the experiments. This does create a lot of pods that do nothing else but raise `SkippedException`.
To make reruns complete faster, this change will ignore these experiments in the first place.
Depends on https://github.com/mozilla/jetstream/pull/599
> Skip experiments early

- tox.ini
Create an environment using pins and not the latest package versions du jour.
> Tox should test with pins

- jetstream/analysis.py
- jetstream/cli.py
- jetstream/logging/__init__.py
- jetstream/statistics.py
- jetstream/tests/integration/test_logging_integration.py
- jetstream/tests/test_cli.py
- requirements.in
- requirements.txt
Fixes https://github.com/mozilla/jetstream/issues/716
This is more complicated than I initially thought. It appears that the registered `BigQueryLogHandler`s get wiped and aren't actually registered to the `logger`s in the dask workers. This explains why we see the logs in the console but not in BigQuery. This also seems to be related to this issue: https://github.com/dask/distributed/issues/2592
As a workaround, we need to register the `BigQueryLogHandler` when dask workers get set up. This is relatively easily possible by writing a dask [WorkerPlugin](https://docs.dask.org/en/latest/setup/custom-startup.html#worker-lifecycle-plugins)
> Dask logging

- jetstream/analysis.py
This looks harmless; it just prints a warning when we trip it, but we may as well fix it.
> Avoid format string error

- jetstream/logging/__init__.py
I'll rerun the failed experiments once this is merged
Error was: ` setup() got an unexpected keyword argument 'worker'`
> Fix dask logging plugin setup

- jetstream/config/default_metrics.toml
- jetstream/config/fenix.toml
- requirements.in
- requirements.txt
A couple things to call out:
* The Fenix metrics were computing total_uri_count incorrectly. I don't think we need to re-run anything because we haven't computed any periods for release experiments that would have used this metric yet. Just under the wire!
* In the dependency update, gitpython==3.1.14 is a downgrade; it looks like .17 was yanked because of uncertainty about whether Python 3.5 support is important; there aren't any functional changes that matter to us.
> Use search_clients_engines_sources_daily vs search_clients_daily

- jetstream/config.py
- jetstream/metadata.py
- jetstream/tests/conftest.py
- jetstream/tests/test_config.py
- jetstream/tests/test_metadata.py
Fixes https://github.com/mozilla/jetstream/issues/820
When writing the outcome configs, a list of `default_metrics` can be defined at the top like:
```yaml
friendly_name = "Test outcome"
description = "Outcome for testing"
default_metrics = ["spam", "organic_search_count"]
[metrics.spam]
data_source = "main"
select_expression = "1"
[metrics.spam.statistics.bootstrap_mean]
[metrics.organic_search_count.statistics.bootstrap_mean]
[metrics.ad_clicks.statistics.bootstrap_mean]
```
The exported metadata will then have the list of `default_metrics` for outcomes.
I also opened a PR to updated the docs: https://github.com/mozilla/experimenter-docs/pull/103
> Allow configuration of default metrics in outcomes

- jetstream/metadata.py
- jetstream/statistics.py
- jetstream/tests/test_metadata.py
Fixes https://github.com/mozilla/jetstream/issues/840
Adds a new `reference_branch` attribute to the experiment metadata:
```json
{
"metrics": {
"view_about_logins": {
"friendly_name": "about:logins viewers",
"description": "Counts the number of clients that viewed about:logins.\n",
"bigger_is_better": true,
"analysis_bases": ["enrollments"]
},
"my_cool_metric": {
"friendly_name": "",
"description": "",
"bigger_is_better": true,
"analysis_bases": ["enrollments"]
}
},
"outcomes": {},
"reference_branch": "b",   // <--- This got added
"schema_version": 3         // <--- Bumped the version to 3
}
```
> Add reference_branch to experiment metadata

- jetstream/config.py
- jetstream/metadata.py
- jetstream/statistics.py
- jetstream/tests/test_metadata.py
This adds `external_config` to the exported experiment metadata:
Unblocks https://github.com/mozilla/experimenter/issues/6200
> External config metadata

- jetstream/analysis.py
- jetstream/tests/integration/test_analysis_integration.py
While re-running the fission experiment, jetstream is running into `Exception while writing resource usage profiling data to BigQuery: 403 Quota exceeded: Your table exceeded quota for imports or query appe
nds per table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas`
disable for now.
> Temporarily disable resource usage logging

- requirements.in
- requirements.txt
re-run update_deps due to ci failing wiht missing hash error:
```
#!/bin/bash -eo pipefail
python3.8 -m venv venv/
venv/bin/pip install --progress-bar off --upgrade -r requirements.txt
[...]
Requirement already satisfied: zict==2.0.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1060)) (2.0.0)
Requirement already satisfied: zipp==3.6.0 in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1066)) (3.6.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from distributed==2021.11.2->-r requirements.txt (line 115)) (56.0.0)
Collecting google-api-core<3.0.0dev,>=1.21.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
google-api-core<3.0.0dev,>=1.21.0 from …
```
> Re-run `update_deps` due to ci failing wiht missing hash error

- jetstream/config.py
- jetstream/tests/test_config.py
This is part one of extracting out configuration into a separate config file. Before doing that I wanted to make this part testable to ensure once it is extracted I can verify that nothing has changed (behaviour wise). Please let me know if you have any comments @scholtzan.
Also, both attributes `metrics_module` and `segments_module` are actually optional now.
> Feat(issue-932): Supported platform configuration - part1

- jetstream/config.py
- jetstream/tests/test_config.py
- platform_config.toml
Now `config_spec_path`, `metrics_module`, and `segments_module` config values get defaulted to platform name and can be overwritten from inside `platform_config.toml` file.
> Feat(issue-932): Supported platform Configuration Part3

- jetstream/experimenter.py
- requirements.in
- requirements.txt
cattrs bumped up to 1.10.0 and type check ignored due to what appears to be a bug in cattrs
See this issue for more info: https://github.com/mozilla/jetstream/issues/995
> cattrs bumped up to 1.10.0 and type check ignored due to what appears to be a bug in cattrs

- jetstream/util.py
> Exception logging for retries exceeded added to get_retry

- .dockerignore
- Dockerfile
Made some tweaks to the docker image to improve the build time (doing copy all after initial pip install)
Added a couple of folders to dockerignore (I don't believe the app needs those) and pip keeps no cache to help reduce the image size:
Not a huge difference.
> tweaked dockerfile and dockerignore

- jetstream/bigquery_client.py
- requirements.in
- requirements.txt
Reverts mozilla/jetstream#1135
We are seeing warnings like `Error while computing statistic deciles for metric qualified_cumulative_days_of_use: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''` that are likely related to this update
> Revert "Update dependencies"

- jetstream/analysis.py
- jetstream/config.py
- jetstream/external_config.py
- jetstream/tests/conftest.py
- jetstream/tests/test_config.py
Follow up to #1200 which had to be reverted due to validation check failing for `jetstream-config` repo as the result of the change.
Commit: 132cc36f089c5c8b47ed18afa98936b79625cc19 should resolve the validation error.
> Fear(cirrus-753): parametise outcome spotlight multi message id part 2 

- jetstream/cli.py
- jetstream/export_json.py
- jetstream/tests/test_cli.py
The log export only occurs right now if analysis succeeds, so we move it into a `finally` block to ensure we export logs in case of error during analysis.
> fix #1333: move log export into a finally block

- jetstream/export_json.py
The root logger is the one that has the bigquery log handler that we want to flush.
> fix #1344: flush logger root handlers

- jetstream/cli.py
- jetstream/export_json.py
Because there may be errors computing weekly analysis, and weekly analysis is only computed once per week, these errors will be aged out of the current export date range (`> analysis_start_time`).
This PR uses the experiment's `enrollment_end_date` to calculate the end of the last weekly analysis window, and uses that timestamp for the error log export filter.
> fix #1436: export errors in current weekly analysis window

- jetstream/tests/test_config.py
I was seeing a local issue with this test where it was retrieving a config with no metrics, causing the test to fail. This change forces the test to get a specific config by slug.
> fix config datasource test by getting specific config

- jetstream/analysis.py
- jetstream/export_json.py
- jetstream/metric.py
- jetstream/tests/conftest.py
- jetstream/tests/data/test_events.ndjson
- jetstream/tests/integration/conftest.py
- jetstream/tests/test_metric.py
This adds some checks for multiple analysis bases (for now this defaults to `enrollments`, `exposures`) and removes some assumptions we previously wanted when only `enrollments` were supported.
> fix #1298: assume multiple analysis_bases and export all results

- jetstream/analysis.py
When adding support for multiple analysis bases, there was a regression introduced for segments. This fixes that regression. The function affected filters data to a given segment, and then filters the segment data to a given analysis_basis.
> fix #1510: sub-filter segment data properly

- jetstream/cli.py
- jetstream/config.py
- jetstream/metadata.py
- jetstream/tests/test_config.py
- jetstream/tests/test_metadata.py
Depends on https://github.com/mozilla/metric-config-parser/pull/148
Blocked by actually moving configs into metric-hub
For https://github.com/mozilla/jetstream/issues/1527
> Load configs from metric hub

- jetstream/export_json.py
Per https://github.com/mozilla/experimenter/issues/8190, we can ignore `EndedException` errors in Experimenter, so we should not export them.
> fix #1593: do not export EndedException logs

- jetstream/pre_treatment.py
- jetstream/statistics.py
- jetstream/tests/test_pretreatment.py
We are adding the `analysis_period_length` to all pre-treatments during analysis because they need to come in dynamically and this removes the need for a more complicated workflow. However, this also means the `analysis_period_length` needs to exist on all pre-treatments even if it is not explicitly used. This PR moves the class field to the parent PreTreatment.
> move analysis_period_length to parent PreTreatment

- jetstream/cli.py
Fixes the following issue on argo:
```
Usage: jetstream run [OPTIONS]
Try ‘jetstream run --help’ for help.
Error: Invalid value for ‘--analysis_periods’ / ‘--analysis-periods’: AnalysisPeriod.OVERALL
time=“2023-05-08T22:34:49 UTC” level=info msg=“sub-process exited” argo=true error=“<nil>”
Error: exit status 2
```
> Use analysis_period default string values in Argo workflow

- jetstream/analysis.py
- jetstream/tests/test_analysis.py
Ignore the `is_enrollment_paused` flag if the enrollment period is overridden via custom config.
> fix #1745: ensure enrollment is not overridden before checking api flag

- jetstream/export_json.py
Looks for certain API errors when a table does not exist to export and instead of failing completely, allows the job to continue and potentially export other tables that do exist.
> fix #1748: ignore gcp api exception if table not found during export

- setup.py
`python_requires` was out of date so I also updated that here
> push latest to version 2023.6.1

- jetstream/analysis.py
- jetstream/export_json.py
- jetstream/metadata.py
- jetstream/metric.py
- jetstream/statistics.py
- jetstream/tests/integration/test_analysis_integration.py
- jetstream/tests/test_analysis.py
- jetstream/tests/test_config.py
- jetstream/tests/test_metadata.py
- jetstream/tests/test_metric.py
- jetstream/tests/test_statistics.py
- requirements.in
- requirements.txt
- setup.py
The goal of this PR is to use the new `mozilla-nimbus-schemas` package to validate data that Jetstream is exporting to Experimenter.
The broader goal of this effort is to provide a single place where shared schemas are defined in order to improve stability of the data relationship between systems within Nimbus.
> fix #1809: migrate duplicative schemas to new package

- jetstream/bigquery_client.py
- jetstream/tests/integration/test_bigquery_client.py
- jetstream/tests/test_bigquery_client.py
Fixes https://github.com/mozilla/jetstream/issues/1741
`jetstream rerun` no longer takes half an hour to actually get started. `last_updated` labels now get updated within seconds
> Speed up updating last_updated timestamps

- jetstream/cli.py
- jetstream/tests/test_cli.py
This should make the error log less cluttered with `EnrollmentNotCompleteException`. Open to debate whether this is a concern or whether we should log something in lieu of raising an exception.
> fix #1881: only create enrollments if enrollment is paused

- jetstream/cli.py
- jetstream/logging/__init__.py
- jetstream/logging/bigquery_log_handler.py
- jetstream/tests/integration/test_analysis_integration.py
- jetstream/tests/integration/test_logging_integration.py
- setup.py
[auto-sizing](https://github.com/mozilla/auto-sizing) logs to the same table as jetstream, so this adds a value to help differentiate.
Separately, I have already added a column to the bigquery table, and will submit a similar PR to `auto-sizing`.
> add source to logging

- requirements.in
- requirements.txt
there was a bug in metric-config-parser for experiments with outcomes that was fixed in the latest version
> bump mcp version to latest 2023.11.1

- jetstream/statistics.py
- jetstream/tests/test_statistics.py
This PR applies result-level deduplication so that there should only be one set of statistics (point estimate/confidence interval) per unique set of result metadata.
> Deduplicate individual statistics

- jetstream/statistics.py
- jetstream/tests/test_statistics.py
- requirements.in
- requirements.txt
Incorporates additional error checks from most recent mozanalysis version. Also catches case where covariate adjustment was configured correctly, but metric was also configured for the other preenrollment analysis basis. In that case, we do not want to attempt to adjust inferences for `PREENROLLMENT_DAYS_28` using `PREENROLLMENT_WEEK`. Additionally, adds check for missing covariate column, logs a warning and falls back to unadjusted inferences in that case. 
Added 2 unit tests for the new fallback cases.
> bump mozanalysis version, add additional fallback case

- .circleci/config.yml
- pyproject.toml
The switch to pyproject evidently had an issue with the deploy CI task
> fix deploy

- jetstream/analysis.py
- jetstream/tests/test_analysis.py
Experiment slugs can begin with a number, while to query a bigquery table beginning with a number, the table name must be wrapped in backticks
> Wrap metrics tables in backticks

- .circleci/config.yml
Greedily removed mypy when adding ruff, just adding it back here (it wasn't removed from the tox config).
> add mypy back to CI

- jetstream/experimenter.py
- jetstream/tests/integration/test_experimenter_api.py
- jetstream/tests/test_experimenter.py
Currently jetstream uses the v6 api and this changes it to use the v8 api instead. It also adds some tests for the api.
> Change jetstream to use v8 api

- jetstream/experimenter.py
- jetstream/tests/test_analysis.py
- jetstream/tests/test_experimenter.py
The naming conventions were previously tied to specific API versions (v1 and v6), but we needed to make them more generic. As part of the transition from v6 to v8, this renames 'v1' to 'legacy' and 'v6' to 'Nimbus' to better reflect current usage.
> Change naming to reflect switch to v8 API

- jetstream/analysis.py
- jetstream/bigquery_client.py
- jetstream/tests/integration/test_bigquery_client.py
Goal here is to add the label to experiment tables whenever they're created, but don't count on it for anything (yet).
```
"experiment_slug": "slug-for-experiment"
```
> feat: add experiment_slug label to experiment tables

- jetstream/analysis.py
- jetstream/bigquery_client.py
- jetstream/tests/integration/test_bigquery_client.py
Reverts mozilla/jetstream#2226
Label values in bigquery are limited to 63 characters, so slugs longer than that cause an error. Seems like we'll have to find an alternate approach (likely update the regex)
> Revert "feat: add experiment_slug label to experiment tables"

- jetstream/analysis.py
- jetstream/bigquery_client.py
- jetstream/tests/integration/test_bigquery_client.py
- jetstream/tests/integration/test_config_integration.py
Ok, round two. We tried storing the experiment slug in the label, but hit a character limit. As far as I can tell, the character limit for descriptions is 1024 instead of 64, so we should be good here. This takes the previous approach and lightly modifies it to use the description instead of a label.
> feat: store experiment slug in description

- jetstream/cli.py
- jetstream/experimenter.py
- jetstream/tests/test_experimenter.py
- requirements.in
- requirements.txt
Segments are made available to jetstream through the API and this allows for them to be stored within the NimbusExperiment object.
> Consume segments in jetstream

- .circleci/config.yml
`gcp-gcr@0.15.x` uses a base image (ubuntu 20.04) that was deprecated and then removed starting 1 Oct. This updates to the latest version of the orb to unblock image deployments to GCR.
> chore: update orb to one with non-removed base image

- jetstream/argo.py
With the argo-server pod restarting yesterday, there are (or were) a few different pods matching the app, and so `items[0]` was not retrieving the correct one. This led to an error and made it difficult to connect to the Argo UI without modifying the command. This updates the help text shown in Jetstream to include a filter that only shows running pods.
I can't think of any instances where this would be a bad idea, but let me know if you have any concerns. In any case, this only changes the log so I don't think it will hurt anything.
> chore: add running status filter to argo ui command

- jetstream/analysis.py
- jetstream/cli.py
- jetstream/tests/test_cli.py
- jetstream/workflows/run.yaml
This came up recently with an experiment that had not configured their statistics properly, but all the metrics were otherwise correct. I also thought this was a good first step towards more discrete executions along the lines of the discrete metric executions I was planning (https://github.com/mozilla/jetstream/pull/2260).
> feat: allow running only statistics

- jetstream/pre_treatment.py
- jetstream/tests/test_pretreatment.py
There were two warnings:
- one complained about setting an incompatible dtype when setting `example_data.iloc[1, 1] = np.inf` in the test. `np.inf` is a float so I just changed the fixture to floats instead of ints.
- second warning was because of a deprecated option `use_inf_as_na` in `RemoveIndefinites`, so now we explicitly change `np.inf` to `np.nan` and then call `dropna`. Apparently this is also faster, but [we don't appear](https://github.com/search?q=org%3Amozilla%20remove_indefinites&type=code) to be using it anywhere anyway, so probably won't matter!
> chore: fix pandas deprecation warnings

- jetstream/analysis.py
- jetstream/cli.py
I tried using this on a real experiment today, and got an error from `table_exists` saying `Invalid table ID "Delayed('calculate_metrics-....')"`.
Previously, the table name was coming from `calculate_metrics` which is a dask.delayed function, so instead I'll get it directly from `_table_name` for the purposes of this.
Other improvements:
- `--statistics-only` option is now a flag
- skip statistics calculations if metrics table doesn't exist (previously just logged warning)
> fix: fix metrics table check in stats_only

- jetstream/cli.py
So there seems to be a way to do a ternary operator like
```
"{{workflow.parameters.statistics_only}} ? '--statistics-only' : ''"
```
in the arguments somewhere in the run.yaml, but I couldn't figure it out. Maybe because it's the end of the week, maybe because it doesn't work in the place I need it, not sure.
Either way, we need to have this fixed to unblock Jetstream executation, so this will have to do for now.
> fix: argo workflow needs stats-only arg to not be a flag

- README.md
- tox.ini
Realized that after some previous changes, we were running mypy twice with the default `tox`, so I switched things up a bit so it should run just once. 
Also took the opportunity to pull out the lint/format commands into their own tox env so they can be run independently from the tests.
> chore: refactor tox.ini

- docs/adr-0003-discrete_metrics_table_structure.md
This lays out the options for how to deal with the new discrete metric execution in terms of storing the results. 
I am leaning towards Option 2 because I think it will be the most straightforward, with the main complexity lying in creating the views to match the current structure. Open to discussion though!
> docs: ADR for results storage with discrete metrics

- jetstream/experimenter.py
- jetstream/tests/test_analysis.py
- jetstream/tests/test_experimenter.py
We don't need to ingest experiments from the v1 API because these are all Normandy, and Normandy is retired. This removes the fetching and creation of Legacy Experiments.
> chore: remove normandy experiments

- platform_config.toml
We aren't using jetstream for cirrus apps yet, and having them included could produce errors that aren't meaningful and that could be confusing to users.
/cc @jaredlockhart @yashikakhurana 
fixes #2441
> chore: remove monitor cirrus from apps

- jetstream/artifacts.py
- jetstream/tests/conftest.py
- jetstream/tests/test_artifacts.py
- pyproject.toml
I noticed that the `latest_image` fn wasn't always getting the actual latest image, and as far as I can tell it was because both the latest and previous-latest images are "updated" when the latest is uploaded: the previous-latest is updated because its tags change, i.e., the `latest` tag is removed. Using the `upload_time` instead of `update_time` should fix this, and in my testing it appears to work.
I also added a max python version, sorted the ruff rules, and fixed a renamed rule (`TCH` --> `TC`).
> fix: get image by upload not update time

- jetstream/statistics.py
This has come up periodically, and so I thought a comprehensive explanation would help myself or any other engineer looking through the code for why there is no absolute data in the results for this statistic.
> chore: add comment about dau statistic output

- jetstream/cli.py
Saw an error from here that appeared to be getting logged with the wrong experiment, and I think it's because we're logging the last experiment in the list, so if there is an error when originally resolving all experiments' configs then it would be logged with the last experiment's slug.
> fix: log actual slug with config resolve error

- jetstream/cli.py
- jetstream/experimenter.py
- jetstream/tests/integration/test_experimenter_api.py
- jetstream/tests/test_cli.py
This is intended to alleviate some load on the Experimenter API that appears to be leading to increasing errors in Jetstream when attempting to request experiment data. The assumption is that at least some of the problem stems from the ever-increasing number of experiments in Experimenter, and the fact that jetstream naively requests all of them and figures out the important ones after-the-fact.
This fix makes it so jetstream can request a specific experiment's config when a slug is configured (e.g., when run manually, or for each workflow launched from the daily airflow task).
I considered iterating over the slugs whenever it wasn't `AllType`, but am a bit wary of running an arbitrary number of API requests, and I think this more specific solution should cover the most common scenarios …
> feat: request single slug from Exp API when possible

- jetstream/bigquery_client.py
- jetstream/config.py
Found another instance of the fuzzy match getting the wrong date. In this case it was in `experiment_table_first_updated`, but went and looked for other possibilities and so I also updated `updated_defaults` similarly to `updated_configs` that I updated previously.
> fix: use specific slug to get last_updated dates

- jetstream/bigquery_client.py
- jetstream/cli.py
- jetstream/experimenter.py
Some QOL improvements:
- fetch by slug when possible in validate (cli)
- don't fetch from API at all if not needed (cli)
- remove unused import (bigquery_client)
- improve error logging (experimenter)
fixes #2631
> chore: improve validate fetch and error logging

- jetstream/analysis.py
Every time I look up a metrics query to investigate issues, I have to manually add in the dataset for it to be valid. This fully qualifies it for convenience.
> chore: fully qualify enrollments table in metrics query

- pyproject.toml
validate fails for users running jetstream locally because of the changes to the dry run function. Pushing a new version with the latest changes should fix it.
> chore: push version 2025.7.1

- jetstream/analysis.py
- jetstream/bigquery_client.py
Problem was an accidental unindent on the statistics part of the `run` function.
> fix: calculate metric stats properly

- .github/workflows/build-and-deploy.yml
This adds another step to the CI to auto approve and merge dependabot PRs if CI succeeds. Based on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#automatically-approving-a-pull-request
Not sure how to test this other than merging and trying it on a dependabot PR
> Auto-approve and merge PRs from dependabot

- .github/workflows/build-and-deploy.yml
I added a personal token under `JETSTREAM_PAT` for both GH Actions and the dependabot context. This should solve the issue in https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions that results in auto-merged dependabot PRs getting stuck in the merge queue
> Use JETSTREAM_PAT instead of GITHUB_TOKEN for auto-approving and merging dependabot PRs

- .github/workflows/build-and-deploy.yml
This should resolve the issue we are seeing:
`GraphQL: Resource not accessible by personal access token (enablePullRequestAutoMerge)`
--auto calls the GraphQL mutation enablePullRequestAutoMerge under the hood, which shouldn't be needed
> Stop auto-merge for dependabot PRs

- .github/workflows/build-and-deploy.yml
Since the PAT doesn't have permissions to merge PRs, removing the dependabot CI step to not have so many failures show up. The only way seems to be creating a new Github App. I'll look into this some time in the future.
> Remove dependabot CI step

- jetstream/analysis.py
- jetstream/dryrun.py
- jetstream/tests/test_analysis.py
I recently added bytes processed to the dry run function's return value, so we can use it here. This is useful for running locally as well as in metric-hub CI.
fixes #2799
> feat: add bytes processed to validation logs
