mozilla/jetstream

.gitignore, pensieve/_version.py, pensieve/experimenter.py, pensieve/tests/test_experimenter.py, setup.py, tox.ini
It's probably helpful to look at these two commits separately; the first adds some Python packaging boilerplate and the second commit adds some support for talking to Experimenter to learn about experiments by hitting the public API and deserializing a subset of the JSON into some native objects.
Follow-up PRs will include actually doing anything useful with that information, like deciding that it's time to run mozanalysis, and then doing it. ✨
Any takes?
=> Hello, Experimenter!

README.md, pensieve/experimenter.py, pensieve/tests/test_experimenter.py, pyproject.toml
Updated README.md and set the line-length for black to 100
=> Add CircleCI shield to README

Dockerfile, bin/entrypoint
Adds a simple Dockerfile that installs the repo package and dependencies, and runs an entrypoint that exercises the experiment list
Part of #4
=> Add dummy entrypoint script and simple Dockerfile

pensieve/experimenter.py, pensieve/tests/test_analysis.py, script/run_experiment_analysis
Only look at pref-flips and addon experiments until we learn how to do other things.
=> Don't analyze rollouts

pensieve/analysis.py, pensieve/experimenter.py, pensieve/tests/test_analysis.py
Use the TimeLimits logic to see if today has just closed an analysis window, making it time to run an analysis. Pull the enrollment length from Experimenter.
@felixlawrence, does this look basically sane?
=> Use mozanalysis to decide whether to run an experiment

pensieve/analysis.py, pensieve/tests/test_analysis.py
I found a mistake in the TimeLimits integration while trying this out on Tuesday's data, oops -- this threw another assertion when we tried to actually run an analysis.
I'll send a PR to have mozanalysis do this.
=> Fix up TimeLimits integration

pensieve/analysis.py, pensieve/cli.py, pensieve/tests/integration/test_analysis_integration.py, pensieve/tests/test_analysis.py
This sits on top of #34 and has Analysis learn the metrics to be computed from the AnalysisConfig object.
To do:
=> Use configuration in Analysis

pensieve/analysis.py, pensieve/tests/integration/test_analysis_integration.py
Fixes https://github.com/mozilla/pensieve/issues/45
This also fixes a bug that prevents statistics data from getting written to BigQuery
=> Create view for statistics tables and bugfix for publishing statistics

pensieve/config.py, pensieve/statistics.py, pensieve/tests/test_statistics.py
Useful as a stat for retention and other binary outcomes.
=> Add a binomial outcome statistic

setup.cfg, setup.py
=> Choose a non-colliding distribution name

.circleci/config.yml, pensieve/analysis.py, pensieve/cli.py, pensieve/config.py, pensieve/experimenter.py, pensieve/statistics.py, pensieve/tests/test_experimenter.py
See https://github.com/mozilla/pensieve/pull/72 (which can be closed)
=> Fix CircleCI pushing images

pensieve/cli.py
Oops. Fixes today's Airflow failure; I tested it this time.
=> Use tz-aware dates everywhere

pensieve/analysis.py, pensieve/cli.py, pensieve/config.py, pensieve/config/default_metrics.toml, pensieve/statistics.py, pensieve/tests/test_config.py
Adds a Deciles statistic, refactors some Statistics code, adds a secret CLI flag, fixes some serialization errors, and allows overriding enrollment periods from config.
=> Add a Deciles statistic, and some demo fixes

pensieve/export_json.py
Follow-up to https://github.com/mozilla/pensieve/pull/106#r450512736
=> Improve statistics_export_to_json naming

pensieve/cli.py, pensieve/config.py, pensieve/tests/test_analysis.py, pensieve/tests/test_config.py
FIx up a few missing pieces needed to implement a demo CFR dashboard.
=> CFR demo fixes

pensieve/config.py, pensieve/tests/test_config.py
Allow the enrollment queries to reference properties of the experiment. 
Simplifies the fallback getter for ExperimentConfiguration.
This was probably an exercise in making a simple thing hard, but:
- creates a proxy object to prevent a template from referencing itself 
recursively
- caches the result of the template expansion at instantiation to make 
sure that any failures happen early
The cached template will be invalid if the ExperimentSpec or 
Experimenter object are mutated after the config spec is resolved, so, 
uh, hopefully nobody will try that.
Closes #98.
=> Template enrollment queries

pensieve/config/default_metrics.toml
=> Add search metrics

pensieve/analysis.py, pensieve/cli.py
There was/is an experiment with start_date and end_date one day apart but a proposed_enrollment of 2 weeks.
=> Fix CLI and enrollment_period issue

jetstream/analysis.py, jetstream/cli.py, jetstream/dryrun.py, script/jetstream-dryrun.js
I created a cloud function that will perform the dry run and return some JSON status. This cloud function is used to validated the generated metrics query when the `dry_run` option is set.
=> Wetter dry run

jetstream/export_json.py
Overall stats tables weren't being exported to JSON; this makes sure that all of the stats tables will get written out.
=> Export overall stat tables

jetstream/analysis.py, jetstream/config.py, jetstream/nimbus.py, jetstream/statistics.py, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/integration/test_featureresolver_integration.py, jetstream/tests/test_nimbus.py, jetstream/tests/test_statistics.py
Addresses https://github.com/mozilla/jetstream/issues/147
=> Refactor Statistics reference_branch

jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/146
=> Improve error handling for experiments with no end date

contibuting.md
Fixes #151.
@shell1, could you confirm this is what we're doing? :)
=> Describe issue triage

jetstream/statistics.py, jetstream/tests/test_config.py, jetstream/tests/test_statistics.py
Attempts to fix https://github.com/mozilla/jetstream/issues/118
=> Run multiple comparisons when requested

jetstream/analysis.py, jetstream/config.py, jetstream/statistics.py, jetstream/tests/data/test_clients_last_seen.ndjson, jetstream/tests/integration/conftest.py, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/test_analysis.py, jetstream/tests/test_config.py
Part of #58. I need to add tests, but does this seem like a reasonable direction?
=> Add support for segments

jetstream/statistics.py
I read the docs wrong and need to dedupe first. 🙃
=> Hold nsmallest right

jetstream/config.py, jetstream/config/default_metrics.toml, jetstream/tests/test_config.py, requirements.in, requirements.txt
Followup to https://github.com/mozilla/jetstream/issues/109
=> Documented metrics

jetstream/experimenter.py, jetstream/tests/test_experimenter.py
Fixes https://github.com/mozilla/jetstream/issues/270
=> Error handling when pulling in Experimenter experiments

Dockerfile
Fixes https://github.com/mozilla/jetstream/issues/288
=> Docker install git

jetstream/bigquery_client.py, jetstream/cli.py, jetstream/tests/test_cli.py
Do less in the Click functions; aspire for them to do nothing more than define an interface and pass arguments directly into other code with a minimum of control flow. The goal is to isolate the parts that are hard to test and defer as much responsibility as possible into systems we can fake.
=> Refactor CLI

jetstream/cli.py
jetstream-config currently failing because of this
=> ArgoExecutorStrategy with dataset_id

jetstream/config.py, jetstream/tests/test_config.py
Fixes https://github.com/mozilla/jetstream/issues/316
=> Fix pre_treatments config parsing

bin/entrypoint, jetstream/cli.py, jetstream/export_json.py, jetstream/workflows/run.yaml
Fix https://github.com/mozilla/jetstream/issues/303
=> Export statistics after experiment finishes analysis

jetstream/argo.py
Fixes https://github.com/mozilla/jetstream/issues/320
=> Refresh access token when fetching Argo status

jetstream/export_json.py
Fixes https://github.com/mozilla/jetstream/issues/324
=> Fix concurrency problems when exporting data

jetstream/bigquery_client.py, jetstream/external_config.py
=> Fix table timestamps

jetstream/analysis.py
=> Validate segments

jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/329
=> Pass None for empty configuration_map

jetstream/cli.py, jetstream/tests/test_cli.py
Be a little more defensive about input; to simplify the click functions, make the Executor decide whether experiments are real.
=> Ensure experiments exist

jetstream/workflows/run.yaml
Fixes https://github.com/mozilla/jetstream/issues/336
I re-ran `bug-1674187-pref-holdback-study-for-quantumbar-v2-release-82-85` for 2020-11-19, this time without problems finishing in 2:09 minutes.
=> Tweak Argo resource config

jetstream/analysis.py, jetstream/tests/test_experimenter.py
Fixes https://github.com/mozilla/jetstream/issues/346
=> Only compare dates when checking if experiment is complete

docs/adr-0001-publishing_metric_docs.md
How does this look as a decision point for publishing our metrics descriptions for dashboard consumers? I almost wonder if this is meaty enough for an ADR but maybe I'm not considering my options fully. :D
cf #296
=> ADR for publishing metrics descriptions

jetstream/argo.py, jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/356 and https://github.com/mozilla/jetstream-config/issues/26
=> Propagate Argo status

jetstream/config.py, jetstream/tests/test_metadata.py
=> Plumb through bigger_is_better flag

jetstream/workflows/run.yaml
Fixes https://github.com/mozilla/jetstream/issues/452
=> Ensure Argo workflow succeeds

jetstream/analysis.py, jetstream/config.py, jetstream/config/fenix.toml, jetstream/experimenter.py, jetstream/tests/conftest.py, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/test_analysis.py, jetstream/tests/test_cli.py, jetstream/tests/test_config.py
Todo:
- Validate
- Figure out how to hook this in
- Come up with a story for redefining data sources depending on the product/channel
=> Add support for Fenix experiments

jetstream/external_config.py, jetstream/metadata.py, jetstream/tests/conftest.py, jetstream/tests/integration/test_external_config_integration.py, jetstream/tests/test_external_config.py
Fixes https://github.com/mozilla/jetstream/issues/510
=> Add commit sha to outcomes metadata

jetstream/cli.py, jetstream/external_config.py, jetstream/tests/test_cli.py
Yep, I added some tests...
(This _should_ make the CI succeed for https://github.com/mozilla/jetstream-config/pull/47)
=> Skip example configs in validate_config

jetstream/analysis.py, jetstream/config.py, jetstream/errors.py, jetstream/tests/test_analysis.py
Facilitates https://github.com/mozilla/jetstream-config/pull/49.
=> Add a `skip` directive to jetstream-config

jetstream/analysis.py
=> Revert "Run metrics queries in shared-prod"

jetstream/dryrun.py
We don't want to do this unconditionally since we have better handling for some other HTTP statuses below, but if get() failed or the response body isn't JSON then something else bad must have happened, so see if we can pull an error message out of that.
=> Raise for a HTTP error if we don't have valid JSON

script/jetstream-dryrun.js
Changes have already been deployed.
=> Increase API timeout in dry run function

jetstream/tests/integration/test_default_configs.py
It'd be nice to have the same safety that we have in jetstream-config here. :)
Closes #473.
=> Validate default configs

jetstream/analysis.py
Mozanalysis needs to know which app to pull enrollments from.
=> Fix Fenix enrollment queries

jetstream/cli.py, jetstream/experimenter.py, jetstream/tests/test_cli.py, jetstream/tests/test_experimenter.py
Fixes https://github.com/mozilla/jetstream/issues/597 and https://github.com/mozilla/jetstream/issues/598
=> Consider external config end_date when determining active experiments

jetstream/argo.py, jetstream/experimenter.py, jetstream/util.py
Should fix https://github.com/mozilla/jetstream/issues/614
=> Increase wait time for fetching argo status

jetstream/config/default_metrics.toml, jetstream/statistics.py
Discussion in https://docs.google.com/document/d/1VmRhTOL50VzygJpe2iStR25XkmtoJZKtMYov0X7k0fE/edit.
Fun question: how will we know which tables were analyzed this way? Does it matter? (Probably not!)
=> Increase trim fraction to 0.5%

jetstream/config/fenix.toml
Match desktop so we get reporting in Experimenter.
=> Rename Fenix sap_search_count to search_count

docs/adr-0002-publishing_statistics_with_analysis_basis.md, requirements.in, requirements.txt
Follow-up to https://github.com/mozilla/jetstream/pull/703#discussion_r645898033
https://github.com/mozilla/jetstream/pull/703 currently implements option 1, but option 2 might also be something we might want to consider.
=> ADR - Changes when working with statistics tables

jetstream/analysis.py, jetstream/metadata.py, jetstream/statistics.py, jetstream/tests/test_metadata.py
Fixes https://github.com/mozilla/jetstream/issues/725
=> Add statistics table schema version to metadata

jetstream/tests/integration/test_analysis_integration.py
Follow-up to https://github.com/mozilla/jetstream/pull/722#pullrequestreview-677606219
This would have also caught https://github.com/mozilla/jetstream/issues/716
=> Add test for logging

jetstream/experimenter.py, jetstream/tests/test_experimenter.py
fixes https://github.com/mozilla/jetstream/issues/817
=> Use new Experimenter v6 date format

docs/proposal-0001-flexible_handling_of_exposure_events.md, jetstream/analysis.py
Proposal for https://github.com/mozilla/jetstream/issues/926
=> Draft proposal for flexibility in handling of exposure events

docs/proposal-0001-flexible_handling_of_exposure_events.md
See https://github.com/mozilla/mozanalysis/issues/144
=> Update flexible exposure handling proposal

jetstream/experimenter.py, jetstream/util.py, requirements.in, requirements.txt
Fixes https://github.com/mozilla/jetstream/issues/972
=> Send user agent when accessing Experimenter API

README.md
CircleCI badge in README.md updated to point at main branch
=> CircleCI badge in README.md updated to point at main branch

.gitignore, jetstream/config.py, jetstream/errors.py, jetstream/external_config.py, jetstream/tests/test_config.py, jetstream/tests/test_external_config.py, requirements.in, requirements.txt
=> feat(issues-843): validate jetstream config

jetstream/external_config.py, jetstream/tests/test_external_config.py
Unblocks adding new outcomes
https://app.circleci.com/pipelines/github/mozilla/jetstream-config/678/workflows/4e0f3e50-3442-4c16-a422-215801f19984/jobs/928
=> Ignore validation checks for unused metrics

jetstream/tests/data/Metadata_v1.0.json, jetstream/tests/data/Statistics_v1.0.json, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/test_metadata.py, jetstream/tests/test_statistics.py
fixes https://github.com/mozilla/jetstream/issues/1093
=> Schema checks

jetstream/config.py, jetstream/external_config.py, jetstream/tests/conftest.py, jetstream/tests/test_config.py
Fear(cirrus-753): parametise outcome spotlight multi message id part 2
=> Fear(cirrus-753): parametise outcome spotlight multi message id part 2

jetstream/cli.py
For https://github.com/mozilla/jetstream-config/pull/226
=> Temporarily ignore function configs

jetstream/cli.py
For https://github.com/mozilla/jetstream-config/pull/226
=> Skip definitions config validation

jetstream/analysis.py, jetstream/experimenter.py, jetstream/metadata.py, jetstream/tests/data/NimbusExperiment_v1.0.json, jetstream/tests/test_experimenter.py, requirements.in, requirements.txt
Fixes https://github.com/mozilla/jetstream/issues/1253
=> Use enrollment end date

jetstream/argo.py
old link is dead, i think this is where it lives now
=> Update argo cli docs link

jetstream/cli.py
For https://github.com/mozilla/metric-hub/pull/35
=> CLI allow multiple --experiment_slug

docs/proposal-0004-jetstream-preview.md
https://github.com/mozilla/jetstream/issues/1528
=> Jetstream preview proposal

jetstream/cli.py
Fixes https://github.com/mozilla/jetstream/issues/1583
We've had a few instances where a config got updated, the rerun got triggered via the CI but took so long that the scheduled nightly rerun did also trigger a rerun got the same experiment.
We determine which experiment needs to be updated by comparing the table timestamps with the config timestamps. The table timestamps got updated after the analysis has finished, however if we update them before then we should be able to prevent more of these cases from happening.
cc @danielkberry
=> Update table timestamps at the beginning of a rerun instead of end

jetstream/analysis.py, jetstream/cli.py, jetstream/tests/test_cli.py, jetstream/workflows/run.yaml
fixes https://github.com/mozilla/jetstream/issues/1570
cc @danielkberry
=> Add --analysis_period parameter to CLI

jetstream/analysis.py, jetstream/export_json.py, jetstream/tests/test_analysis.py
Fixes https://github.com/mozilla/jetstream/issues/1743
Also see: https://mozilla.slack.com/archives/CF94YGE03/p1684341353479919
=> Ignore EnrollmentNotCompleteException during validation

jetstream/cli.py, jetstream/experimenter.py, jetstream/preview.py
Fixes https://github.com/mozilla/jetstream/issues/1757
=> Consider draft experiments in preview

jetstream/analysis.py, jetstream/bigquery_client.py, jetstream/metric.py, jetstream/statistics.py, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/test_statistics.py, requirements.in, requirements.txt
Fixes https://github.com/mozilla/jetstream/issues/1796
Depends on https://github.com/mozilla/metric-config-parser/pull/253
=> Population Ratio statistic

jetstream/workflows/run.yaml
This might reduce the number of killed workers
=> Increase memory per pod

jetstream/statistics.py, jetstream/tests/integration/test_analysis_integration.py, jetstream/tests/test_statistics.py
Reverts mozilla/jetstream#2018
=> Revert "fix #763: compute stats for all branches as reference"

.circleci/config.yml, Dockerfile, README.md
=> fix #2048: workaround pip bug in dep resolution with `--no-deps`

jetstream/analysis.py
Change this to a warning and add extras to populate the logs table and error dashboard.
=> add extras to covariate logging warning

jetstream/cli.py
=> fix: catch all config resolution errors

jetstream/analysis.py, jetstream/cli.py, jetstream/statistics.py, jetstream/tests/test_analysis.py, jetstream/workflows/run.yaml
Some things that I noticed while doing discrete metrics work that I think is worth keeping, but unrelated to that work. Better to split it out to reduce risk.
=> chore: minor fixes and QOL improvements

jetstream/bigquery_client.py, jetstream/tests/integration/test_bigquery_client.py, jetstream/tests/test_bigquery_client.py
fixes #2309
should I also be removing `tables_matching_regex`?
=> chore: use tables_matching_description instead of tables_matching_regex

jetstream/bigquery_client.py
When we started using `tables_matching_description`, we had an old print statement in there that I forgot to delete. I realized it's kind of helpful to have logging in here so I kept it and added some more around deletions.
=> chore: add more logging to table deletions for visibility

jetstream/workflows/run.yaml
=> chore: set secondsAfterCompletion TTL
